// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Explicitly load .env.local
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7: Connection URLs moved from schema.prisma to here
    // For migrations, use DIRECT_URL (direct connection, not pooled)
    url: env("DIRECT_URL"),
  },
});
