import "server-only";
import { NextRequest, NextResponse } from "next/server";
import { requireAdmin } from "@/lib/auth/guards";
import { randomUUID } from "crypto";
import { logAuditEvent } from "@/lib/audit";

export const runtime = "nodejs";

/**
 * POST /api/admin/manual-upload
 * 
 * Admin-only endpoint to manually create:
 * - Attorneys (User + AttorneyProfile)
 * - Clients (Policy Holders)
 * - Beneficiaries
 */
export async function POST(req: NextRequest) {
  try {
    const admin = await requireAdmin();
    const body = await req.json();
    const { type, data } = body;

    if (!type || !["attorney", "client", "beneficiary"].includes(type)) {
      return NextResponse.json(
        { error: "Invalid type. Must be 'attorney', 'client', or 'beneficiary'" },
        { status: 400 }
      );
    }

    switch (type) {
      case "attorney": {
        const {
          email,
          firstName,
          lastName,
          phone,
          lawFirm,
          barNumber,
          licenseState,
        } = data;

        if (!email || !firstName || !lastName || !barNumber || !licenseState) {
          return NextResponse.json(
            { error: "Email, firstName, lastName, barNumber, and licenseState are required for attorneys" },
            { status: 400 }
          );
        }

        const { findUnique: findUniqueUser, create: createUser, create: createProfile } = await import("@/lib/db");
        
        // Check if user already exists
        const existingUser = await findUniqueUser("users", { email });

        if (existingUser) {
          return NextResponse.json(
            { error: "User with this email already exists" },
            { status: 400 }
          );
        }

        // Create user with ATTORNEY role
        // Generate a placeholder clerkId for manually created users (format: manual_<uuid>)
        // This satisfies the required unique constraint and can be updated later if the user signs up with Clerk
        const userId = randomUUID();
        const placeholderClerkId = `manual_${randomUUID()}`;
        const now = new Date().toISOString();
        
        const user = await createUser("users", {
          id: userId,
          clerkId: placeholderClerkId,
          email,
          firstName,
          lastName,
          phone: phone || null,
          barNumber: barNumber || null,
          role: "ATTORNEY",
          // Note: createdAt and updatedAt are auto-generated by the database
        } as Record<string, unknown>) as {
          id: string;
          email: string;
          firstName: string;
          lastName: string;
        };

        // Create attorney profile
        const profile = await createProfile("attorney_profiles", {
          userId: user.id,
          licenseStatus: "ACTIVE",
          licenseState: licenseState || null,
          lawFirm: lawFirm || null,
          verifiedAt: now,
          appliedAt: now,
          createdAt: now,
          updatedAt: now,
        } as Record<string, unknown>) as {
          id: string;
          licenseStatus: string;
        };

        await logAuditEvent({
          userId: admin.id,
          action: "ATTORNEY_CREATED",
          metadata: { 
            email, 
            firstName, 
            lastName, 
            barNumber, 
            createdBy: admin.id,
            manuallyCreated: true,
            placeholderClerkId: placeholderClerkId,
            note: "Manually created by admin. User will need to sign up with Clerk to link their account.",
            resourceId: user.id,
          },
        });

        return NextResponse.json({
          success: true,
          message: "Attorney created successfully",
          user: {
            id: user.id,
            email: user.email,
            firstName: user.firstName,
            lastName: user.lastName,
          },
          profile: {
            id: profile.id,
            licenseStatus: profile.licenseStatus,
          },
        });
      }

      case "client": {
        const {
          orgId,
          email,
          firstName,
          lastName,
          phone,
          dateOfBirth,
          addressLine1,
          addressLine2,
          city,
          state,
          postalCode,
          country,
        } = data;

        if (!orgId || !email || !firstName || !lastName) {
          return NextResponse.json(
            { error: "Firm (organization), email, firstName, and lastName are required for policy holders" },
            { status: 400 }
          );
        }

        const { findMany: findManyClients, findUnique: findUniqueOrg, create: createDbRecord } = await import("@/lib/db");

        const org = await findUniqueOrg("organizations", { id: orgId });
        if (!org) {
          return NextResponse.json({ error: "Organization not found" }, { status: 404 });
        }

        // Check if client already exists
        const existingClients = await findManyClients("clients", {
          where: { email },
          limit: 1,
        });

        if (existingClients && existingClients.length > 0) {
          return NextResponse.json(
            { error: "Client with this email already exists" },
            { status: 400 }
          );
        }

        const clientId = randomUUID();
        const dateOfBirthValue = dateOfBirth ? new Date(dateOfBirth).toISOString() : null;
        const now = new Date().toISOString();

        // Create client
        const client = await createDbRecord("clients", {
          id: clientId,
          orgId,
          email,
          firstName: firstName,
          lastName: lastName,
          phone: phone || null,
          dateOfBirth: dateOfBirthValue,
          addressLine1: addressLine1 || null,
          addressLine2: addressLine2 || null,
          city: city || null,
          state: state || null,
          postalCode: postalCode || null,
          country: country || null,
          createdAt: now,
          updatedAt: now,
        } as Record<string, unknown>) as {
          id: string;
          firstName: string;
          lastName: string;
          email: string;
        };

        await logAuditEvent({
          userId: admin.id,
          action: "CLIENT_CREATED",
          metadata: {
            email,
            firstName,
            lastName,
            orgId,
            createdBy: admin.id,
            resourceId: client.id,
            manuallyCreated: true,
          },
        });

        return NextResponse.json({
          success: true,
          message: "Client created successfully",
          client: {
            id: client.id,
            email: client.email,
            firstName: client.firstName,
            lastName: client.lastName,
          },
        });
      }

      case "beneficiary": {
        const {
          clientId,
          firstName,
          lastName,
          relationship,
          email,
          phone,
          dateOfBirth,
          addressLine1,
          addressLine2,
          city,
          state,
          postalCode,
          country,
        } = data;

        if (!clientId || !firstName || !lastName) {
          return NextResponse.json(
            { error: "clientId, firstName, and lastName are required for beneficiaries" },
            { status: 400 }
          );
        }

        const { findUnique: findUniqueClient, create: createBeneficiary } = await import("@/lib/db");
        
        // Verify client exists
        const clientExists = await findUniqueClient("clients", { id: clientId });

        if (!clientExists) {
          return NextResponse.json(
            { error: "Client not found" },
            { status: 404 }
          );
        }

        const beneficiaryId = randomUUID();
        const dateOfBirthValue = dateOfBirth ? new Date(dateOfBirth).toISOString() : null;
        const now = new Date().toISOString();

        // Create beneficiary
        const beneficiary = await createBeneficiary("beneficiaries", {
          id: beneficiaryId,
          clientId: clientId,
          firstName: firstName,
          lastName: lastName,
          relationship: relationship || null,
          email: email || null,
          phone: phone || null,
          dateOfBirth: dateOfBirthValue,
          addressLine1: addressLine1 || null,
          addressLine2: addressLine2 || null,
          city: city || null,
          state: state || null,
          postalCode: postalCode || null,
          country: country || null,
          createdAt: now,
          updatedAt: now,
        } as Record<string, unknown>) as {
          id: string;
          firstName: string;
          lastName: string;
        };

        await logAuditEvent({
          userId: admin.id,
          action: "BENEFICIARY_CREATED",
          metadata: { clientId, firstName, lastName, createdBy: admin.id, resourceId: beneficiary.id },
        });

        return NextResponse.json({
          success: true,
          message: "Beneficiary created successfully",
          beneficiary: {
            id: beneficiary.id,
            firstName: beneficiary.firstName,
            lastName: beneficiary.lastName,
          },
        });
      }

      default:
        return NextResponse.json(
          { error: "Invalid type" },
          { status: 400 }
        );
    }
  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    const errorStatus = error && typeof error === "object" && "status" in error && typeof error.status === "number" ? error.status : 500;
    console.error("Manual upload error:", error);
    return NextResponse.json(
      { error: errorMessage || "Failed to create record" },
      { status: errorStatus }
    );
  }
}

