import { NextResponse } from "next/server";
import { auth, currentUser } from "@clerk/nextjs/server";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { randomUUID } from "crypto";
import { findUnique, update, create } from "@/lib/db";

export async function POST() {
  const authResult = await auth();
  const userId = authResult.userId;
  if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const cu = await currentUser();
  if (!cu?.id) return NextResponse.json({ error: "Missing Clerk user" }, { status: 400 });

  const email = cu.emailAddresses?.[0]?.emailAddress ?? null;

  try {
    // Check if user already exists
    type UserRecord = {
      id: string;
      clerkId: string;
      email: string;
      roles?: string[];
    };

    const existingUser = await findUnique<UserRecord>("users", { clerkId: cu.id });

    if (existingUser) {
      // Update existing user
      const updated = await update<UserRecord>("users", { id: existingUser.id }, {
        email: email ?? "",
        updatedAt: new Date().toISOString(),
      } as Record<string, unknown>);

      return NextResponse.json({ user: updated });
    } else {
      // Create new user with generated ID
      const newUser = await create<UserRecord>("users", {
        id: randomUUID(),
        clerkId: cu.id,
        email: email ?? "",
        roles: ["USER"],
        // Note: createdAt and updatedAt are auto-generated by the database
      } as Record<string, unknown>);

      return NextResponse.json({ user: newUser });
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ error: errorMessage }, { status: 500 });
  }
}
