import { NextRequest, NextResponse } from "next/server";
import { auth, currentUser } from "@clerk/nextjs/server";

export async function POST(_req: NextRequest) {
  // Only allow in development
  if (process.env.NODE_ENV === 'production') {
    return NextResponse.json({ error: "Not available in production" }, { status: 403 });
  }

  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
    }

    const clerkUser = await currentUser();
    if (!clerkUser) {
      return NextResponse.json({ error: "Clerk user not found" }, { status: 401 });
    }

    const email = clerkUser.emailAddresses?.[0]?.emailAddress;
    const firstName = clerkUser.firstName;
    const lastName = clerkUser.lastName;
    const clerkRole = (clerkUser.publicMetadata as { role?: string })?.role;

    if (!email) {
      return NextResponse.json({ error: "No email found" }, { status: 400 });
    }

    const { findUnique: findUniqueUser, create: createUser, update: updateUser } = await import("@/lib/db");
    const { randomUUID } = await import("crypto");
    
    // Check if user exists
    const existing = await findUniqueUser<{ id: string; email: string; role: string }>("users", { clerkId: userId });

    if (existing) {
      // Update existing user
      const updated = await updateUser("users", { id: existing.id }, {
        email,
        firstName,
        lastName,
        role: (clerkRole === "attorney" ? "ATTORNEY" : existing.role) || "ATTORNEY",
        updatedAt: new Date().toISOString(),
      } as Record<string, unknown>) as { id: string; email: string; role: string };
      return NextResponse.json({ 
        success: true, 
        action: "updated",
        user: {
          id: updated.id,
          email: updated.email,
          role: updated.role,
        }
      });
    } else {
      // Create new user
      const now = new Date().toISOString();
      const created = await createUser("users", {
        id: randomUUID(),
        clerkId: userId,
        email,
        firstName,
        lastName,
        role: "ATTORNEY",
        // Note: createdAt and updatedAt are auto-generated by the database
      } as Record<string, unknown>) as { id: string; email: string; role: string };
      return NextResponse.json({ 
        success: true, 
        action: "created",
        user: {
          id: created.id,
          email: created.email,
          role: created.role,
        }
      });
    }
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    console.error("Error in create-user endpoint:", message);
    return NextResponse.json({ 
      error: message,
    }, { status: 500 });
  }
}

